source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'RNNativeDialogExample' do
  rnpath = '../../node_modules/react-native'
  pod 'React', path: rnpath, subspecs: [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTImage',
  ]
  pod 'yoga', path: "#{rnpath}/ReactCommon/yoga"
  pod 'DoubleConversion', podspec: "#{rnpath}/third-party-podspecs"
  pod 'glog', podspec: "#{rnpath}/third-party-podspecs"
  pod 'Folly', podspec: "#{rnpath}/third-party-podspecs"

  pod 'react-native-native-dialog', path: '../../ios/'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
#    if target.name == 'React'
#      target.remove_from_project
#    end

    if ['PopupDialog'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end

  end
end
