platform :ios, '9.0'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'RNNativeDialogExample' do
  # Pods for RNNativeDialogExample
  rnpath = '../../node_modules/react-native'

  pod 'React', :path => rnpath
  pod 'React-Core', :path => "#{rnpath}/React"
  pod 'React-DevSupport', :path => "#{rnpath}/React"
  pod 'React-RCTActionSheet', :path => "#{rnpath}/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{rnpath}/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{rnpath}/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{rnpath}/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{rnpath}/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{rnpath}/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{rnpath}/Libraries/Settings"
  pod 'React-RCTText', :path => "#{rnpath}/Libraries/Text"
  pod 'React-RCTVibration', :path => "#{rnpath}/Libraries/Vibration"
  pod 'React-RCTWebSocket', :path => "#{rnpath}/Libraries/WebSocket"

  pod 'React-cxxreact', :path => "#{rnpath}/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{rnpath}/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{rnpath}/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{rnpath}/ReactCommon/jsinspector"
  pod 'yoga', :path => "#{rnpath}/ReactCommon/yoga"

  pod 'DoubleConversion', podspec: "#{rnpath}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', podspec: "#{rnpath}/third-party-podspecs/glog.podspec"
  pod 'Folly', podspec: "#{rnpath}/third-party-podspecs/Folly.podspec"

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  use_native_modules!
end
